### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/PackageDev#156]
This is similar to the other issue https://github.com/SublimeText/PackageDev/issues/129, but now the lines and file are different. It happened when I was editing, opening, deleting creating new copies of the `User/ColorHighlighter.sublime-settings` file:
```
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 604, in on_query_completions
    res = vel.on_query_completions(prefix, locations)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\__init__.py", line 149, in on_query_completions
    return completions_aggregator(self.view, prefix, point)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 474, in value_completions
    completions = self._value_completions_for(key)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 565, in _value_completions_for
    completions = self._marked_default_completions(completions, default)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 587, in _marked_default_completions
    value = item[1]
TypeError: 'NoneType' object is not subscriptable
```

<details>
<p>

```
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 604, in on_query_completions
    res = vel.on_query_completions(prefix, locations)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\__init__.py", line 149, in on_query_completions
    return completions_aggregator(self.view, prefix, point)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 474, in value_completions
    completions = self._value_completions_for(key)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 565, in _value_completions_for
    completions = self._marked_default_completions(completions, default)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 587, in _marked_default_completions
    value = item[1]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 604, in on_query_completions
    res = vel.on_query_completions(prefix, locations)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\__init__.py", line 149, in on_query_completions
    return completions_aggregator(self.view, prefix, point)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 474, in value_completions
    completions = self._value_completions_for(key)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 565, in _value_completions_for
    completions = self._marked_default_completions(completions, default)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 587, in _marked_default_completions
    value = item[1]
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 604, in on_query_completions
    res = vel.on_query_completions(prefix, locations)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\__init__.py", line 149, in on_query_completions
    return completions_aggregator(self.view, prefix, point)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 474, in value_completions
    completions = self._value_completions_for(key)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 565, in _value_completions_for
    completions = self._marked_default_completions(completions, default)
  File "D:\SublimeText\Data\Packages\PackageDev\plugins_\settings\known_settings.py", line 587, in _marked_default_completions
    value = item[1]
TypeError: 'NoneType' object is not subscriptable
reloading settings Packages/User/ColorHighlighter.sublime-settings
```
</p>
</details><br>

```python
File: PackageDev/plugins_/settings/known_settings.py
584:         default_completions = set()
585:         is_list = isinstance(default, list)
586:         for item in completions:
587:             value = item[1]
588:             if is_list and value in default or value == default:
589:                 item = format_completion_item(value, default=True)
590:             default_completions.add(item)
591:         return default_completions
```

___

Related:

1. https://github.com/SublimeText/PackageDev/issues/129 TypeError: argument of type 'NoneType' is not iterable

**Comment by evandrocoan** [comment]
Thanks for fixing it!
