### ISSUE TITLE
Menu Options Disabled - New issue

### ISSUE THREAD

**Issue by juancarmo** [SublimeText/PackageDev#249]
I know there is a thread called like this one, with the same problem. 

Thing is the reason seems to be different.

The menu under "Tools ->Packages->Package Development" ... is disabled

Console output:
```
startup, version: 3143 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /home/usuario
packages path: /home/usuario/.config/sublime-text-3/Packages
state path: /home/usuario/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/usuario/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
top level value must be an array
pre session restore time: 0.059773
startup time: 0.151122
first paint time: 0.169456
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.01-sublime_lib
reloading plugin 0_package_control_loader.50-pathlib
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin File Rename.file_rename
reloading plugin MarkdownPreview.markdown_preview
reloading plugin MarkdownPreview.markdown_settings
reloading plugin MarkdownPreview.markdown_wrapper
reloading plugin PHP Companion.PHP Companion
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageDev._logging
reloading plugin PackageDev.main
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "main in /home/usuario/.config/sublime-text-3/Installed Packages/PackageDev.sublime-package", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "plugins_ in /home/usuario/.config/sublime-text-3/Installed Packages/PackageDev.sublime-package", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "plugins_.open_package in /home/usuario/.config/sublime-text-3/Installed Packages/PackageDev.sublime-package", line 22, in <module>
AttributeError: 'module' object has no attribute 'ListInputHandler'
reloading plugin Phpcs.phpcs
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2019-06-29 18:52:44, next run at 2019-06-29 19:52:44 or after
Unable to open /home/usuario/.config/sublime-text-3/Packages/Default/Preferences.sublime-settings
```
OS: Linux Mint (`Linux user 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`)

I also executed the "Package Control: Satisfy Dependencies" command ... but nothing

**Comment by juancarmo** [comment]
I updated to the last version (3207) and I have the menu option running ok. Please proceed to close this issue if you think so.

**Comment by FichteFoll** [comment]
Your build must have been older than 3154 because that's where input handlers have been added, i.e. before version 3.1. I should probably update the package's minimum build required in the meta data.
