### ISSUE TITLE
[bug] the plugin show exception error if dependency is missing

### ISSUE THREAD

**Issue by babygau** [SublimeText/PackageDev#298]
hi, i got this error when installing the plugin.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 274, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/PackageDev.sublime-package/main.py", line 24, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/PackageDev.sublime-package/plugins_/__init__.py", line 3, in <module>
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1425, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/babygau/Library/Application Support/Sublime Text 3/Installed Packages/PackageDev.sublime-package/plugins_/color_scheme_dev.py", line 8, in <module>
```

**Comment by FichteFoll** [comment]
The actual error message is missing, unfortunately.
Does a restart of ST fix it? Dependencies should be installed properly by Package Control on installation of PD.

**Comment by babygau** [comment]
you're right, restart sublime does install missing dependency. i think this is because of package control. it should handle the exception nicer
thank you!!!
